module Slop.Audio
  ( Audio(..)
  , MusicAsset(..)
  , ChunkAsset(..)
  , Track
  , TrackPool
  , PoolPolicy(..)
  , playMusic
  , playMusicLoop
  , playSound
  , createTrackPool
  , createTrackPoolFrom
  , playPool
  , playPoolLoop
  , playPoolPriority
  , playPoolPriorityLoop
  , stopPool
  , trackPlaying
  , crossfadeTo
  , crossfadeToLoop
  , updateBlend
  , createTrack
  , destroyTrack
  , playOn
  , playOnLoop
  , stopTrack
  ) where

import Slop.Internal
