{-# LANGUAGE DuplicateRecordFields #-}

-- | Explicit GPU resources, shaders, bindings, compute work, and 3D drawing.
module Slop.GPU
  ( Texture(..)
  , TextureUsage(..)
  , TextureDesc(..)
  , textureDesc
  , textureDescSize
  , Positive
  , mkPositive
  , positive
  , Size2D
  , Size3D
  , mkSize2D
  , mkSize3D
  , size2D
  , size3D
  , size2DToTuple
  , size3DToTuple
  , Threads2D
  , Threads3D
  , mkThreads2D
  , mkThreads3D
  , threads2D
  , threads3D
  , threads2DToInts
  , threads3DToInts
  , createTexture2D
  , createTexture2DSize
  , createNoiseTexture2D
  , createNoiseTexture2DSize
  , createNoiseTexture3D
  , createNoiseTexture3DSize
  , NoiseType(..)
  , NoiseSettings(..)
  , defaultNoiseSettings
  , loopNoise2D
  , loopNoise3D
  , VertexAttrFormat(..)
  , VertexAttr(..)
  , VertexLayout(..)
  , Primitive(..)
  , Mesh(..)
  , Mesh3D
  , mesh3D
  , Vertex3D(..)
  , Pipeline(..)
  , VertexShader(..)
  , FragmentShader
  , Shader
  , Shader2D
  , ShaderCounts(..)
  , ReflectedStorageAccess(..)
  , ReflectedBindingType(..)
  , ReflectedBinding(..)
  , ReflectedShaderLayout
  , shaderLayoutFromReflection
  , shaderCountsFromReflection
  , BindingSlot(..)
  , Shader2DLayout(..)
  , TargetFormat(..)
  , BlendMode(..)
  , DepthMode(..)
  , GraphicsDesc(..)
  , defaultGraphics
  , graphicsPipeline
  , defaultCompute
  , computeDescFromReflection
  , computePipeline
  , Binding(..)
  , ComputePipeline(..)
  , ComputeDesc(..)
  , ComputeBinding(..)
  , NamedComputeBinding(..)
  , computeBindingsFromReflection
  , createMesh
  , createTransientMesh
  , createMesh3D
  , createTransientMesh3D
  , destroyMesh
  , createPipeline
  , destroyPipeline
  , swapchainFormat
  , createVertexShader
  , destroyVertexShader
  , createFragmentShader
  , createFragmentShaderReflected
  , destroyFragmentShader
  , createShader2D
  , createShader2DReflected
  , destroyShader2D
  , destroyComputePipeline
  , dispatchCompute
  , spriteLayout
  , mesh3DLayout
  , spritePipeline
  , spriteBindings
  , spriteMesh
  , spriteMeshTransient
  , vUniform
  , vUniformBytes
  , fUniform
  , fUniformBytes
  , fSampler
  , fSamplerWith
  , fStorageTexture
  , computeUniform
  , computeUniformBytes
  , computeSampler
  , computeSamplerWith
  , computeStorageTexture
  , computeStorageTextureRW
  , RenderTarget
  , createRenderTarget
  , createRenderTargetSize
  , withRenderTarget
  , destroyTarget
  , render
  , output
  , postProcess
  , TargetRef(..)
  , RenderPlan
  , PlanM
  , PassM
  , plan
  , pass
  , runPlan
  , passClear
  , passDraw
  , passBlit
  , passWithShader
  , passPostProcess
  , Sampler(..)
  , SamplerDesc(..)
  , SamplerFilter(..)
  , SamplerMipmap(..)
  , SamplerAddress(..)
  , SamplerCompare(..)
  , defaultSamplerDesc
  , createSampler
  , destroySampler
  , As3D
  , Camera3D(..)
  , camera3D
  , camera3DView
  , camera3DProj
  , camera3DViewProj
  , camera3DMVP
  , basic3D
  , AsMesh
  , asMesh
  , drawMesh
  , ShaderUniform(..)
  , shaderUniformSized
  , shaderUniformBytesSized
  , ShaderStage(..)
  , ShaderBindings(..)
  , NamedUniform(..)
  , emptyShaderBindings
  , setShaderBindings
  , setShader2DBindings
  , getShaderBindings
  , resolveNamedUniforms
  , resolveReflectedUniforms
  , normalizeBindings
  , normalizeBindingsSparse
  , normalizeUniforms
  , ShaderAsset(..)
  , Shader2DAsset(..)
  , ReflectedShader2DAsset(..)
  , Shader2DLayoutAsset(..)
  , VertexShaderAsset(..)
  , ComputePipelineAsset(..)
  , PipelineAsset(..)
  , SamplerAsset(..)
  , TextureDescAsset(..)
  , NoiseTexture2DAsset(..)
  , NoiseTexture3DAsset(..)
  , withShaderBindings
  , withShader
  ) where

import Slop.Internal
