-- | Direct and asynchronous resource loading with explicit status and cleanup.
module Slop.Resource
  ( Resource(..)
  , withResource
  , releaseResource
  , Texture
  , Font
  , Text
  , loadTexture
  , destroyTexture
  , loadFont
  , loadFontSDF
  , closeFont
  , createText
  , destroyText
  , AssetId
  , AnyAssetId(..)
  , AssetStatus(..)
  , AssetUpdate
  , AssetLoader(..)
  , AssetThread(..)
  , TextureAsset(..)
  , FontAsset(..)
  , SdfFontAsset(..)
  , TextAsset(..)
  , loadAsset
  , loadAssetResult
  , loadAssetAsync
  , processMainAssets
  , awaitAsset
  , awaitAssetResult
  , awaitAssetUpdate
  , awaitAssetUpdateResult
  , getAsset
  , assetReady
  , getAssetStatus
  , removeAsset
  , removeAssets
  , removeAssets_
  , removeAllAssets
  , enableHotReload
  , disableHotReload
  , reloadAssetAsync
  ) where

import Slop.Internal
